### ISSUE TITLE
The function of the get_optim_policies()

### ISSUE THREAD

**Issue by xasd2003** [qijiezhao/pseudo-3d-pytorch#2]
I found a problem that when I used the function get_optim_policies(), I got an error "ValueError: New atomic module type: <class 'torch.nn.modules.batchnorm.BatchNorm2d'>. Need to give it a learning policy".   I change the code "elif isinstance(m, torch.nn.BatchNorm3d)" into "elif isinstance(m, torch.nn.BatchNorm3d) or isinstance(m, torch.nn.BatchNorm2d):".

Another question is that I don't find "lr_mult" and "decay_mult" arguments in pytorch. Do these parameters affect the learning rate?

**Comment by qijiezhao** [comment]
The first problem is caused by the absence of lr setting with layer BN2D. In the author's paper, the BN after res5 is a 2DBN, so BN2D should be considered.  your solution is great, and I have already added this in the code. 

Of course PyTorch doesn't understand the two params, they are actually generated to adjust the learning rate. like the following:

     optimizer=torch.optim.SGD(polices, lr_init)
     def adjust_learning_rate(optimizer, epoch, lr_steps):
         lr=lr_init* $some num to decay$
         certain_param=optimizer.param_groups[x] #x=2 for instance
         certain_param['lr']=lr* certain_param['lr_mult']

so, the solution is to write your custom adjust_learning_rate() method to utilize these two params.
